### PR TITLE
displaying project stars as tool tip fixes #62

### LINKED ISSUE #62: Display project stars or similar meta-information along side each result.
This could be helpful, to judge credibility of results without going to github.

### PR DESCRIPTION
**Pull request by prudhvije**
Will add tests in separate PR.

### CODE REVIEW

**Comment by prudhvije** [comment]
image

**Comment by ScrapCodes** [comment]
Can you display the tooltip as --> Repo Stars: 264

**Comment by prudhvije** [comment]
Yeah. Update the same. Currently we are not displaying the tool tip for leaf nodes(files). Do we need to display the same tool tip for files also?

**Comment by prudhvije** [comment]
image

**Pull request closed without merging**
