### PR TITLE
tabbed ui for plugin where right tab shows top n results fixes #54

### LINKED ISSUE #54: Tabbed UI for intellij idea plugin.
Create a tabbed UI for intellij idea plugin, where left tab lists all the source instances and right tab lists top N suggestions with mupltiple tiny editors stacked.

### PR DESCRIPTION
**Pull request by prudhvije**

### CODE REVIEW

**Comment by ScrapCodes** [comment]
Can you screenshots ?

**Comment by prudhvije** [comment]
screenshot from 2015-05-07 13 51 06

image

**Comment by prudhvije** [comment]
Made tinyEditor readonly.

**Comment by ScrapCodes** [comment]
1. I am unable to scroll
2. Can you reverse sort on the number of lines of usages.

**Pull request closed without merging**
